#version: '3.8'

services:
  # --- 1. СЕРВІС ТОВАРІВ (Backend) ---
  product_service:
    build: ./product_service
    container_name: pos_product_service
    restart: always
    ports:
      - "8001:8000"
    volumes:                   
      - ./product_service:/app
    environment:
      # Зв'язок з базою даних (postgres_db - це назва сервісу нижче)
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/products_db
      - RABBITMQ_URL=amqp://hits_admin:hits_password@rabbitmq:5672/
    depends_on:
      postgres_db: 
        condition: service_healthy  # <--- Чекати, поки база скаже "Я здорова"

  finance_worker:
    build: ./finance_service 
    container_name: pos_finance_worker
    restart: always
    command: python -u finance_worker.py 
    volumes:
      - ./finance_service:/app 
    environment:
      - DATABASE_URL=postgresql://user:password@finance_db:5432/finance_db
      - RABBITMQ_URL=amqp://hits_admin:hits_password@rabbitmq:5672/
    depends_on:
      - finance_db
      - rabbitmq      
  
  # 🔥 НОВИЙ СЕРВІС: API Фінансів
  finance_api:
    build: ./finance_service
    container_name: pos_finance_api
    restart: always
    # Запускаємо сервер FastAPI на порту 8002
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    volumes:
      - ./finance_service:/app
    environment:
      - DATABASE_URL=postgresql://user:password@finance_db:5432/finance_db
    depends_on:
      - finance_db

# 🔥 НОВИЙ СЕРВІС: API Клієнтів (CRM)
  customer_api:
    build: ./customer_service
    container_name: pos_customer_api
    restart: always
    ports:
      - "8003:8003" # Сервіс працюватиме на порту 8003
    volumes:
      - ./customer_service:/app
    environment:
      # Підключаємося до нашої нової БД customer_db
      - DATABASE_URL=postgresql://user:password@customer_db:5432/customers_db
      - RABBITMQ_URL=amqp://hits_admin:hits_password@rabbitmq:5672/
    depends_on:
      - customer_db

  # 🔥 ДРУГИЙ МІКРОСЕРВІС-ВОРКЕР (Склад)
  inventory_worker:
    build: ./product_service
    container_name: pos_inventory_worker
    restart: always
    command: python -u inventory_worker.py 
    volumes:
      - ./product_service:/app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/products_db
      - RABBITMQ_URL=amqp://hits_admin:hits_password@rabbitmq:5672/
    depends_on:
      - postgres_db
      - rabbitmq

  # --- 2. БАЗА ДАНИХ ТОВАРІВ (PostgreSQL) ---
  postgres_db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d products_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    container_name: pos_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    volumes:
      # Зберігаємо дані на диску, щоб не зникали при перезапуску
      - postgres_data:/var/lib/postgresql/data

  # --- БАЗА ДАНИХ ФІНАНСІВ ---
  finance_db:
    image: postgres:13
    container_name: pos_finance_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    ports:
      - "5433:5432" # Прокидаємо на інший порт, щоб не конфліктувало з основною БД
    volumes:
      - finance_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d finance_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- БАЗА ДАНИХ КЛІЄНТІВ (CRM) ---
  customer_db:
    image: postgres:13
    container_name: pos_customer_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customers_db
    ports:
      - "5435:5432" # Прокидаємо на вільний порт 5435
    volumes:
      - customer_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d customers_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- 3. СЕРВІС КОШИКА (Backend) ---
  order_service:
    build: ./order_service
    container_name: pos_order_service
    restart: always
    environment:
      # Зв'язок з Redis
      - REDIS_HOST=redis_db
    depends_on:
      postgres_db:
        condition: service_healthy

  # --- 4. БАЗА ДАНИХ КОШИКА (Redis) ---
  redis_db:
    image: redis:alpine
    container_name: pos_redis
    restart: always

  # --- 5. ВХІДНІ ВОРОТА (Nginx) ---
  frontend:  # <-- НОВА НАЗВА (було nginx або gateway)
    build: ./frontend
    container_name: pos_frontend # <-- НОВЕ ІМ'Я КОНТЕЙНЕРА
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - product_service
      - order_service
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pos_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Порт для спілкування між мікросервісами
      - "15672:15672" # Порт для крутого WEB-інтерфейсу адміністратора
    environment:
      RABBITMQ_DEFAULT_USER: hits_admin
      RABBITMQ_DEFAULT_PASS: hits_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # НОВИЙ СЕРВІС: API Gateway (Nginx)
  api_gateway:
    image: nginx:alpine
    container_name: pos_api_gateway
    restart: always
    ports:
      - "8088:80" # Фронтенд тепер буде стукати на порт 8080!
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product_service
      - finance_api

# Оголошуємо томи для зберігання даних
volumes:
  postgres_data:
  rabbitmq_data:
  finance_data:
  customer_data:
