"""add_product_and_variant_ids_to_order_items

Revision ID: 85b1cbaec4dd
Revises: ee6667d8b951
Create Date: 2026-04-04 14:08:45.113258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b1cbaec4dd'
down_revision: Union[str, Sequence[str], None] = 'ee6667d8b951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'variant_id')
    op.drop_column('order_items', 'product_id')
    # ### end Alembic commands ###
