"""decouple_orders_and_crm

Revision ID: ee6667d8b951
Revises: 3123d228513b
Create Date: 2026-03-21 07:31:49.552660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6667d8b951'
down_revision: Union[str, Sequence[str], None] = '3123d228513b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    # ### end Alembic commands ###
